### ISSUE TITLE
Is there a way to set the proxy?

### ISSUE THREAD

**Issue by snowcxt** [EvolveLabs/electron-updater#24]
When I run the updater on my company server and I need to pass through a proxy to reach http://registry.npmjs.org/

Is there a way to setup the proxy for electron-updater?

**Comment by justinmchase** [comment]
Hmm, maybe. It definitely _aught to_ do this. It sounds like a very important scenario.

It's using `got` to do all requests, which [supports proxies](https://www.npmjs.com/package/got#proxy). I'm not sure how to detect if you need a proxy or not though, if some of your users are behind a proxy and some are not then we'll have to detect the system proxy settings I think?

However, it may be possible to work around this. It's generally recommended that instead of connecting directly to `npmjs.org` you should [setup your own npm proxy server](https://github.com/EvolveLabs/electron-updater#hosting-your-own-npm-server). If you setup this proxy server inside your corporate network then all of your users should be able to access that directly. If you set it up outside of your network, you could configure it to run on port 80 and then maybe, depending on how your proxy works, you may be able to connect to it directly.

Otherwise, we may need to patch the updater to detect the local systems proxy settings and then use those settings to make requests. 

Working behind corporate firewalls is a pretty important scenario I think so I am happy to work with you to try to get this to work seamlessly. That being said, I am kind of slammed with work right now so any pull requests or even follow ups with research findings would be extremely helpful. Thanks.

**Comment by snowcxt** [comment]
I think this package just needs to provide an api that users can manually setup the proxy for the app.

**Comment by snowcxt** [comment]
Or could you provide an error handler that I can info users to manually download the latest installer?

**Comment by justinmchase** [comment]
> Or could you provide an error handler that I can info users to manually download the latest installer?

* #25 Add api to allow error message window to be customizable.
* #26 Add an api to allow users to specify proxy information.

It's going to be a little bit before I can work on this but PR's welcome.

**Comment by snowcxt** [comment]
I created a PR: https://github.com/EvolveLabs/electron-updater/pull/27. It's ugly but works. You guys can refactor the code later. I need this feature. Could you guys publish this code as soon as possible?

**Comment by snowcxt** [comment]
I created a PR: https://github.com/EvolveLabs/electron-updater/pull/28. You guys can take a look.

**Comment by justinmchase** [comment]
I'm going to close this and use #26 to consolidate proxy features.
