### ISSUE TITLE
upgraded from 1.3.0. The updater doesn't work anymore

### ISSUE THREAD

**Issue by snowcxt** [EvolveLabs/electron-updater#30]

**Comment by michaelzoidl** [comment]
What package do you updated to 1.3.0? 
Have a similar issue (the updater breaks sometimes), maybe that's the same reason.
I have to check this tonight.

(fyi, would be great if you add more data to a github-issue, i'm not a electron-updater-dev, but for me it would be cool to check if this also affects my scenario.

**Comment by justinmchase** [comment]
Do you have any error logs or a description of how its not working? Or even better a public plugin I can use to test with?

FYI I'm no longer with this organization but I will fork it and help you solve this last issue since I think I added a regression while hurrying.

**Comment by snowcxt** [comment]
no error logs. It needs super long time to check the version and when I restart the app, the "Updating" window will be showing up forever.

**Comment by michaelzoidl** [comment]
In my case it just get's a 404 - tried with the official electron-example-plugin and a second one from my npm account.

Here is a short video how it looks like when i start the app with enabled updater:
[http://mjz.io/8hg0c.mp4](http://mjz.io/8hg0c.mp4)

And i logged the IPC Stuff:
```
➜  electron-cd  electron .
EventEmitter {
  domain: null,
  _events:
   { ATOM_BROWSER_REQUIRE: [Function],
     ATOM_BROWSER_GLOBAL: [Function],
     ATOM_BROWSER_CURRENT_WINDOW: [Function],
     ATOM_BROWSER_CURRENT_WEB_CONTENTS: [Function],
     ATOM_BROWSER_CONSTRUCTOR: [Function],
     ATOM_BROWSER_FUNCTION_CALL: [Function],
     ATOM_BROWSER_MEMBER_CONSTRUCTOR: [Function],
     ATOM_BROWSER_MEMBER_CALL: [Function],
     ATOM_BROWSER_MEMBER_SET: [Function],
     ATOM_BROWSER_MEMBER_GET: [Function],
     ATOM_BROWSER_DEREFERENCE: [Function],
     ATOM_BROWSER_GUEST_WEB_CONTENTS: [Function],
     ATOM_SHELL_NAVIGATION_CONTROLLER: [Function],
     ATOM_SHELL_SYNC_NAVIGATION_CONTROLLER: [Function],
     ATOM_SHELL_GUEST_VIEW_MANAGER_CREATE_GUEST: [Function],
     ATOM_SHELL_GUEST_VIEW_MANAGER_ATTACH_GUEST: [Function],
     ATOM_SHELL_GUEST_VIEW_MANAGER_DESTROY_GUEST: [Function],
     ATOM_SHELL_GUEST_VIEW_MANAGER_SET_SIZE: [Function],
     ATOM_SHELL_GUEST_VIEW_MANAGER_SET_ALLOW_TRANSPARENCY: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_WINDOW_OPEN: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_WINDOW_CLOSE: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_WINDOW_METHOD: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_WINDOW_POSTMESSAGE: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_WINDOW_OPENER_POSTMESSAGE: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_WEB_CONTENTS_METHOD: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_GET_GUEST_ID: [Function] },
  _eventsCount: 26,
  _maxListeners: undefined }
Checking validity.
execPath:/Users/michaelzoidl/.nvm/versions/node/v0.12.0/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron
copy appDir: /Users/michaelzoidl/.nvm/versions/node/v0.12.0/lib/node_modules/electron-prebuilt/dist/Electron.app
  updateDir: /Users/michaelzoidl/Library/Application Support/@michaelzoidl/electron-cd/updater/0.33.1
Launching update process:
  args: '{"appName":"@michaelzoidl/electron-cd","publisher":"@michaelzoidl/electron-cd","cwd":"/Users/michaelzoidl/Code/experimental/electron-cd","exe":"/Users/michaelzoidl/.nvm/versions/node/v0.12.0/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron","argv":["."]}'
  exe: /Users/michaelzoidl/Library/Application Support/@michaelzoidl/electron-cd/updater/0.33.1/Contents/MacOS/Electron
  cwd:  /Users/michaelzoidl/Code/experimental/electron-cd
  updateDir: /Users/michaelzoidl/Code/experimental/electron-cd/node_modules/electron-updater
```

**Comment by justinmchase** [comment]
If you guys install the `electron-updater-tools` globally you can use some command line tools to help debug also:

```
$ npm install electron-updater-tools -g
$ elup check
$ elup update
```

@michaelzoidl The 404 seems to mean that something expected is missing, obviously you don't have enough information to figure that out and that's a problem. I need to be passing back more information clearly. That being said, try running `elup check` and it should show you what is out of date and being updated. Then you can check in the `dependencies` section and look at the versions and compare them to whats on npm.

Also, there is an updater log file that gets put into (on mac) `/Users/{user name}/Library/Application Support/{app name}/logs/updater.log`. That will have some information about which projects it was trying to update.

Sorry about this. I would recommend that you guys stick with `0.1.3` until the regressions are resolved and error reporting is improved.

**Comment by justinmchase** [comment]
@michaelzoidl I am able to repro the 404 after some testing.

It appears to be an electron bug unfortunately :( What version are you using specifically?

Here's what i learned from debugging.

After updating the error output a bit I was able to grab this info:
```
[26/09/2015:16:05:33:259:error:06808]{ err: 
   { [HTTPError: Response code 404 (Not Found)]
     message: 'Response code 404 (Not Found)',
     code: undefined,
     host: 'registry.npmjs.org',
     hostname: 'registry.npmjs.org',
     method: 'GET',
     path: '/bytebuffer/undefined',
     statusCode: 404,
     statusMessage: 'Not Found' },
  dir: 'e:\\code\\electron-updater-sample\\release\\app\\node_modules\\electron-mumble\\node_modules\\protobufjs\\node_modules\\bytebuffer' }
```

It doesn't really have anything to do with bytebuffer and you can see that it's asking for `/bytebuffer/undefined` which is obviously wrong. It turns out that at this line:

https://github.com/EvolveLabs/electron-updater/blob/master/lib/update.js#L102

It's not properly propagating an error when it happens which is why it looks for an 'undefined' version. So when that's fixed you can see that the real error is actually in this line:

https://github.com/EvolveLabs/electron-updater/blob/master/lib/update.js#L71

Basically the reply being sent to us is a mangled buffer and `JSON.parse` somewhere down inside is puking.

It took quite a bit of debugging because it doesn't repro when run in iojs and switching to request or using raw http modules doesn't fix it. Finally I looked at electron and found this in their v0.33.2 release notes:

> * Fix length of Buffer becoming 0 when there are lots of Buffer created.
> * Fix crash when there is external ArrayBuffer created with pointers to addresses outside the heap.

I looked at my version and determined that I was using `v0.33.1`, I updated electron and boom it started working. 

So which version of electron are you using? There are multiple places that I had to update to get it to work right:
```
$ npm install eletron-prebuilt@0.33.3 -g
$ npm install electron-prebuilt@0.33.3 --save
```
I then also had to edit my script that calls electron-packager to have `--version=0.33.3`. 

I'm working on some patches that will improve better error logging and error propagation. I am also looking at changing the cache.js file to process a single item at a time if your electron version is lower than `0.33.2` as that also seems to fix it (though run slower).

**Comment by justinmchase** [comment]
version `0.2.2` published, it has some better error logging, minor bug fixes. Also, be sure to use electron `>=0.33.3`.
