### ISSUE TITLE
Silent updates

### ISSUE THREAD

**Issue by sindresorhus** [EvolveLabs/electron-updater#6]
I really like the idea of just using npm for packages and updates. Makes it a lot easier than the way Atom does it.

What I want though is silent updates without bothering users. Like Chrome.

Meaning:

- The update is downloaded in the background
- The user is never bothered about it, but there are events to notify if wanted.
- When the user decides to quit the app and start it again, the new version is started.
- To use this module it should just require a simple oneliner. Something like: `require('electron-updater')()`

**Comment by justinmchase** [comment]
It actually does that already :)

There are 3 kinds of things to update: the app itself, its dependencies and plugins.

Plugins are silently updated if possible. Meaning, while your app is running, if a new version of a plugin becomes available then it will silently download it side-by-side your currently running version and on next launch it will just load that update instead. There is an 'udpateAvailable' event that fires so you can notify users through the UI.

If you develop the majority of your code in plugins then most of your updates will be silent.

The only time a non-silent update happens is if a "dependency" of the app itself is missing or if the app itself has an update. If your installer has no dependencies by default (except `electron-updater` of course) then it will force it into update mode on first launch which will get the latest version even for older downloads of the installer.

**Comment by sindresorhus** [comment]
> if the app itself has an update

Why can't this be silent? That's really what I'm looking for.

**Comment by justinmchase** [comment]
Ah, well even as I'm writing this I'm having thoughts on how I could make it work. 

But the primary challenge is that a) you can't update `electron.exe` itself while its running. Similarly if you overwrite dependencies under `node_modules` then depending on what is already loaded or not you can end up with non-deterministic results for the currently running application. And since npm/node doesn't support side-by-side versions of modules you would need to side-by-side the entire application.

Typically (in windows at least) you have a top level link to the main .exe of the program you're trying to run so it's tricky to have side-by-side versions. Thus, when the app or dependencies need updates, what it does right now is to copy electron into a temp folder then run it from there and update the original app.

But there are things we can do to either solve it completely or at least make it faster such as:

a) download all the tarballs ahead of time then notify the user of an update. So the update process, while still not idea, would be much faster.

b) figure out a way to side-by-side the entire app. Which would probably result in a simple .exe that goes at the root that knows how to launch electron as a child process in a sub-folder.

myapp.exe
myapp.config
  /v0.0.1/myapp.exe
  /v0.0.2/mapp.exe

Where the root myapp.exe looks at myapp.config which has the current version to use and then fires up the more specific version as a child process. I think that could be doable. :)

**Comment by sindresorhus** [comment]
Might also be worth to look into how Atom does it. Maybe any missing APIs that's needed to achieve this could be implemented in Electron.
