### ISSUE TITLE
spawn EACESS error

### ISSUE THREAD

**Issue by mhkeller** [EvolveLabs/electron-updater#9]
![screen shot 2015-07-14 at 01 55 37 am](https://cloud.githubusercontent.com/assets/498744/8667306/ce38bf44-29cb-11e5-95fc-86c26c15faa6.png)

I first thought this was a path escaping issue (not escaping the space) so I added `tmpExecPath.replace(/ /g, '\\ ')` at command.js:152 but that didn't do anything. 

I then ran `chmod +x` on `/Users/mike/Library/Application Support/updater/0.28.3/Electron` and that seemed to work when testing locally but it gives me the same error after I build the application.

**Comment by mhkeller** [comment]
I'm running iojs v2.3.3 on OS X 10.10.3

**Comment by justinmchase** [comment]
Hey thanks! We have been investigating this also, I believe I fixed it this morning. Do a pull or `npm update` and try again. There are some new errors I'm still investigating about pipes but if you dismiss them the app will run as expected. I believe those are happening due to the process closing while there are still messages pending.

**Comment by mhkeller** [comment]
Thatnks. That error is gone but I've got a new one. I'm running electron-prebuilt 0.29.2 and building in that version as well. I set the package.json of one of my dependencies below the one listed in the app package.json.

The app runs and quits with this in the console.
````
Launching update process:
  args: '{"appName":"newslynx-electron","publisher":"newslynx-electron","cwd":"/Users/mike/wrk/projects/newslynx/newslynx-electron","exe":"/Users/mike/wrk/projects/newslynx/newslynx-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron","argv":["."]}'
  exe: /Users/mike/Library/Application Support/newslynx-electron/updater/0.29.2/Contents/MacOS/Electron
  cwd:  /Users/mike/wrk/projects/newslynx/newslynx-electron
  updateDir: /Users/mike/wrk/projects/newslynx/newslynx-electron/node_modules/electron-updater
update required
````

 When I then run `electron .` I get these pop up errors in succession. 

![screen shot 2015-07-14 at 20 38 57 pm](https://cloud.githubusercontent.com/assets/498744/8688302/5e577f7e-2a68-11e5-8363-40b46d56a2ab.png)
![screen shot 2015-07-14 at 20 39 26 pm](https://cloud.githubusercontent.com/assets/498744/8688306/700fa250-2a68-11e5-9d9f-a5725854018a.png)

When I build the app and run it. It properly quits and I get the installing screen. When I try and relaunch the app it says that the module express could not be found so it seems that it hasn't run `npm install` after pulling the latest?

**Comment by mhkeller** [comment]
updated with more screenshots

**Comment by justinmchase** [comment]
Those first two errors I know about and am looking into. I think they're happening because the process is closing suddenly, while Im still trying to log some things. But dismissing them should do no harm and the app should still run. 

However that last error is concerning. I'll try to explain what is "supposed to happen" and then I'll look at what you have on github and see if I can see anything problematic.

When you run the updater like in the README example the first thing it will do is attempt to detect if your app "is valid". An app is invalid if any of its dependencies are missing, or if any of its plugins are missing. It uses the package.json to determine `dependencies`, it ignores `devDependencies`. The versions matter also, if you have a version locally that doesn't match the package.json then it will attempt to update (`update required`).

At this point it will attempt to copy electron over to a temp directory then it will re-run that version of electron passing in some arguments telling it where your app is and where the updater is. This will then spin through your dependencies, fetch them from npm, and unpack them into the right sub directories. It _doesn't_ run `npm install`. This is important to note because npm install does a variety of other things, including compiling native modules and runs arbitrary scripts. We can't really do those things on users computers reliably so we can only dumbly get packages and unpack them and fetch pre-compiled binaries.

It appears that `express` is a dependency of the dependency `newslynx`. It should be downloading subdependencies. Do you have newslynx installed globally or locally?

If you look in your node_modules, under your app, what do you see? It appears to be loading newslynx but then it's sub dependencies are missing or only partially there?

**Comment by justinmchase** [comment]
The EPIPE errors should be gone now and the updater should be working on OSX. Are there any other issues you're still dealing with that I need to address here @mhkeller ?
